apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  template:
    spec:
      containers:
      - name: jobmanager
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
