apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  template:
    spec:
      containers:
      - name: jobmanager
        env:
        - name: FLINK_CONF_DIR
          value: /etc/flink
        volumeMounts:
        - name: flink-config
          mountPath: /etc/flink
      volumes:
      - name: flink-config
        configMap:
          name: flink-config
